# Generated by Django 2.2.9 on 2019-12-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_catalog', '0002_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
