# Generated by Django 2.2.9 on 2019-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_catalog', '0003_registation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
