# Generated by Django 2.2.9 on 2019-12-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
